site_name: Biopet User Manual
pages:
- Home: 'index.md'
- General:
    - Config: 'general/config.md'
    - Requirements: 'general/requirements.md'
    - Memory behaviour: 'general/memory.md'
    - About: 'general/about.md'
    - License: 'general/license.md'
- Pipelines:
    - Basty (Snp typing): 'pipelines/basty.md'
    - Bam2Wig: 'pipelines/bam2wig.md'
    - Carp (chip-seq): 'pipelines/carp.md'
    - Flexiprep (QC): 'pipelines/flexiprep.md'
    - Gears (Metagenome): 'pipelines/gears.md'
    - Gentrap (RNA-seq): 'pipelines/gentrap.md'
    - Mapping (Alignment): 'pipelines/mapping.md'
    - Sage: 'pipelines/sage.md'
    - Shiva (variantcalling): 'pipelines/shiva.md'
    - TinyCap (smallRNA): 'pipelines/tinycap.md'
    - Toucan (Annotation): 'pipelines/toucan.md'
- Tools:
    - AnnotateVcfWithBed: 'tools/AnnotateVcfWithBed.md'
    - SamplesTsvToJson: 'tools/SamplesTsvToJson.md'
    - BedToInterval: 'tools/bedtointerval.md'
    - BastyGenerateFasta: 'tools/BastyGenerateFasta.md'
    - BedToInterval: 'tools/bedtointerval.md'
    - BedtoolsCoverageToCounts: 'tools/bedtoolscoveragetocounts.md'
    - BiopetFlagstat: 'tools/BiopetFlagstat.md'
    - CheckAllelesVcfInBam: 'tools/CheckAllelesVcfInBam.md'
    - ExtractAlignedFastq: 'tools/ExtractAlignedFastq.md'
    - FastqSplitter: 'tools/FastqSplitter.md'
    - FindRepeatsPacBio: 'tools/FindRepeatsPacBio.md'
    - MpileupToVcf: 'tools/MpileupToVcf.md'
    - Sagetools: 'tools/sagetools.md'
    - WipeReads: 'tools/WipeReads.md'
    - VcfFilter: 'tools/VcfFilter.md'
    - VepNormalizer: 'tools/VepNormalizer.md'
- Release notes:
    - 0.7.0: 'releasenotes/release_notes_0.7.0.md'
    - 0.6.0: 'releasenotes/release_notes_0.6.0.md'
    - 0.5.0: 'releasenotes/release_notes_0.5.0.md'
    - 0.4.0: 'releasenotes/release_notes_0.4.0.md'
    - 0.3.2: 'releasenotes/release_notes_0.3.2.md'
    - 0.3.1: 'releasenotes/release_notes_0.3.1.md'
    - 0.3.0: 'releasenotes/release_notes_0.3.0.md'
- Developer:
    - Getting Started: 'developer/getting-started.md'
    - Code Style: 'developer/code-style.md'
    - Example Dependecies: 'developer/example-depends.md'
    - Example Pipeline: 'developer/example-pipeline.md'
    - Example Tool: 'developer/example-tool.md'
    - Example Pipeable: 'developer/example-pipeable.md'
    - Scala docs: 'developer/scaladocs.md'
#- ['developing/Setup.md', 'Developing', 'Setting up your local development environment']
#theme: readthedocs
repo_url: https://github.com/biopet/biopet
